preset: recommended

risky: false

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - phpdoc_separation
  - phpdoc_summary
  - phpdoc_align
  - phpdoc_order
  - no_singleline_whitespace_before_semicolons
  - trailing_comma_in_multiline_array
  - phpdoc_var_without_name

#finder:
#  exclude:
#    - "tests"
#  name:
#    - "*.php"
#  not-name:
#    - "*Stub.php"
#  contains:
#    - "Foo"
#  not-contains:
#    - "config"
#  path:
#    - "foo/Stuff"
#  not-path:
#    - "libraries"
#  depth:
#    - "< 3"