language: php
php:
  - 5.6
  - 7.0
  - nightly

before_install:
  - ./travis-before-install.sh
  - composer self-update

install:
  - composer install

before_script:
  - bin/console doctrine:schema:update --force

script:
  - bin/phpunit
  - bin/phpcs -p --standard=PSR2 --exclude=Generic.Files.LineLength src/ tests/
