language: php
php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - bin/phpunit
  - bin/phpcs -p -n --standard=PSR2 src/ tests/
