language: php
php:
  - 5.5
  - 5.6
  - 7
  - nightly

before_install:
  - ./travis-before-install.sh
  - composer self-update

install:
  - composer install

before_script:
  - bin/console doctrine:schema:update --force

script:
  - bin/phpunit
  - bin/phpcs -p -n --standard=PSR2 src/ tests/
