language: php
php:
  - 7.0
  - 7.1
  - nightly

before_install:
  - ./travis-before-install.sh

install:
  - composer install

before_script:
  - bin/console doctrine:schema:update --force

script:
  - bin/phpunit --coverage-clover=coverage.xml
  - bin/phpcs -p --standard=PSR2 --exclude=Generic.Files.LineLength src/ tests/

after_success:
    - bash <(curl -s https://codecov.io/bash)
