language: php
php:
  - 7.0
  - 7.1
#  - nightly # dependencies incompatible with PHP 7.2

before_install:
  - ./travis-before-install.sh
  - composer self-update

install:
  - composer install

before_script:
  - bin/console doctrine:schema:update --force

script:
  - bin/phpunit
  - bin/phpcs -p --standard=PSR2 --exclude=Generic.Files.LineLength src/ tests/
