<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Game;
use AppBundle\Entity\User;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param int $limit
     * @return Collection|Game[]
     */
    public function findAvailableForUser(User $user, $limit)
    {
        $criteria = new Criteria();
        $expr = Criteria::expr();

        $criteria
            ->where($expr->neq('user1', $user))
            ->andWhere($expr->isNull('user2'))
            ->setMaxResults($limit)
            ->orderBy(['id' => 'DESC'])
        ;

        return $this->matching($criteria);
    }
}
