imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      file
        file:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 14
        loggly:
            type:   loggly
            token:  "%loggly_token%"
            level:  warning
            tag:    "%loggly_tag%"
        login:
            type:     stream
            path:     "%kernel.logs_dir%/auth.log"
            level:    warning
            channels: security
        console:
            type:  console

fos_http_cache:
    cache_control:
        rules:
            # match everything to set defaults
            -
                match:
                    path: ^/
                headers:
                    overwrite: false
                    cache_control: { public: true, max_age: 0, s_maxage: 600 }
                    etag: true
                    vary: [Authorization, Accept]
