app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /

users_v1:
    resource: 'AppBundle\Controller\UsersController'
    type: rest
    prefix: /v1
    name_prefix: temp_v1_

users_v2:
    resource: 'AppBundle\Controller\UsersControllerV2'
    type: rest
    prefix: /v2
    name_prefix: temp_v2_

# @todo routing_v1.yml etc. (maybe import the correct one)
#routing_v1:
#    type: rest
#    resource: "routing_v1.yml"
games_v1:
    resource: app.controller.game
    type: rest
    prefix: /v1
    name_prefix: api_v1_

events_v1:
    resource: app.controller.event
    type: rest
    parent: games_v1
    name_prefix: api_v1_
