doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /doc

cors:
    resource: app.controller.cors
    type: rest

routing_v1:
    resource: routing_v1.yml
    type: rest
