users_v1:
    resource: AppBundle\Controller\UserController
    type: rest
    prefix: /v1
    name_prefix: api_v1_

games_v1:
    resource: AppBundle\Controller\GameController
    type: rest
    prefix: /v1
    name_prefix: api_v1_

events_v1:
    resource: AppBundle\Controller\EventController
    type: rest
    parent: games_v1
    name_prefix: api_v1_
