games_v1:
    resource: app.controller.game
    type: rest
    prefix: /v1
    name_prefix: api_v1_

events_v1:
    resource: app.controller.event
    type: rest
    parent: games_v1
    name_prefix: api_v1_
