app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /

users_v1:
    resource: 'AppBundle\Controller\UsersController'
    type: rest
    prefix: /v1
    name_prefix: v1_

users_v2:
    resource: 'AppBundle\Controller\UsersControllerV2'
    type: rest
    prefix: /v2
    name_prefix: v2_

# @todo routing_v1.yml etc. (maybe import the correct one)
games_v1:
    resource: games_controller
    type: rest
    prefix: /v1
    name_prefix: v1_
