security:
    providers:
        api_key:
            id: app.security.api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false

        cors:
            pattern: ^/(v\d+)/
            methods: [OPTIONS]
            security: false

        new_game:
            pattern: ^/(v\d+)/games$
            methods: [POST]
            security: false

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: app.security.api_key_authenticator
            provider: api_key
