security:
    providers:
        api_key:
            id: AppBundle\Security\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false

        doc:
            pattern: ^/doc
            security: false

        cors:
            pattern: ^/(v\d+)/
            methods: [OPTIONS]
            security: false

        new_user:
            pattern: ^/(v\d+)/users$
            methods: [POST]
            security: false

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: AppBundle\Security\ApiKeyAuthenticator
            provider: api_key
