services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Exception}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        exclude: '../../src/AppBundle/Controller/CorsController.php'
        public: true
        calls:
            - method: setContainer
        tags: ['controller.service_arguments'] # to inject into controllers actions

    AppBundle\Security\ApiKeyAuthenticator:
        arguments:
            $logger: '@monolog.logger.security'

    AppBundle\Security\ApiKeyManager:
        arguments:
            $secret: '%secret%'

    AppBundle\Repository\UserRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['AppBundle:User']

    AppBundle\Repository\GameRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['AppBundle:Game']

    AppBundle\Repository\EventRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['AppBundle:Event']

    AppBundle\Controller\ExceptionController:
        parent: fos_rest.exception.controller
        autowire: false
        autoconfigure: false
        public: true

    AppBundle\EventListener\CorsListener:
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    AppBundle\EventSubscriber\EntitySubscriber:
        tags:
            - { name: doctrine.event_subscriber }
