# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    game_repository:
        class: AppBundle\Entity\GameRepository
        factory: [@doctrine, getRepository]
        arguments: ['AppBundle:Game']

    games_controller:
        class: AppBundle\Controller\GamesController
        arguments: [@doctrine.orm.default_entity_manager, @game_repository]
        calls:
            - [setContainer, [@service_container]]

    app.controller.events_controller:
        class: AppBundle\Controller\EventsController
        arguments: [@doctrine.orm.default_entity_manager, @game_repository]
        calls:
            - [setContainer, [@service_container]]

    entity.listener:
        class: AppBundle\EventListener\EntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    # to set a fallback for SerializedNameAnnotationStrategy https://github.com/schmittjoh/serializer/issues/334
    jms_serializer.camel_case_naming_strategy:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'
