# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.api_key_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false

    app.security.api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider

    app.entity.game_repository:
        class: AppBundle\Entity\GameRepository
        factory: [@doctrine, getRepository]
        arguments: ['AppBundle:Game']

    app.entity.event_repository:
        class: AppBundle\Entity\EventRepository
        factory: [@doctrine, getRepository]
        arguments: ['AppBundle:Event']

    app.controller.game:
        class: AppBundle\Controller\GamesController
        arguments: [@doctrine.orm.default_entity_manager, @app.entity.game_repository]
        calls:
            - [setContainer, [@service_container]]

    app.controller.event:
        class: AppBundle\Controller\EventsController
        arguments: [@doctrine.orm.default_entity_manager, @app.entity.event_repository]
        calls:
            - [setContainer, [@service_container]]

    app.event_listener.entity_listener:
        class: AppBundle\EventListener\EntityListener
        arguments: [@security.token_storage]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: prePersist }

    # to set a fallback for SerializedNameAnnotationStrategy https://github.com/schmittjoh/serializer/issues/334
    jms_serializer.camel_case_naming_strategy:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'
