# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    game.repository:
#        class: AppBundle\Entity\GameRepository
#
#    games_controller:
#        class: AppBundle\Controller\GamesController
#        arguments: [@doctrine.]
