<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @param Game $game
     * @param string $eventType
     * @param int $gt With Id greater than
     * @return Collection
     */
    public function findForGameByType(Game $game, $eventType = null, $gt = null)
    {
        $criteria = new Criteria();
        $expr = $criteria->expr();

        $criteria->where($expr->eq('game', $game));
        if ($eventType !== null) {
            $criteria->andWhere($expr->eq('type', $eventType));
        }
        if ($gt !== null) {
            $criteria->andWhere($expr->gt('id', $gt));
        }

        return $this->matching($criteria);
    }
}
